signUpUrl: http://localhost:5500/register.html
mainUrl: http://localhost:5500/main.html

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 10
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
  # datasource:
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:tcp://localhost/~/throne


