spring:
  application:
    name: landOfRex
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true
  datasource:
    initialize: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod
  redis:
    port: 6379
    host: localhost
  jackson:
    serialization:
      write-dates-as-timestamps: false


logging.level:
  org.hibernate.SQL: debug
  org.springframework:
    security: debug
#  org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true



