services:
  frontend:
    image: react-app
    build:
      context: .  # Set the build context to the parent directory
      dockerfile: LandofRex/Dockerfile  # Specify Dockerfile location within the build context
    ports:
      - "3001:80"
    networks:
      - app-network
    volumes:
      - /usr/share/nginx/html:/app/dist  # Map build output to Nginx directory
    command: ["npm", "run", "build"]  # Run the build command only


networks:
  app-network:
    driver: bridge


