version: '3.8'

services:
  backend:
    image: spring-app
    build:
      context: ./backend/landOfRex  # Backend Dockerfile 위치
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

  frontend:
    image: react-app
    build:
      context: ./LandofRex  # Frontend Dockerfile 위치
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

